export const a = [
  ["afraid", "/əˈfreɪd/", "adj", "When someone is afraid, they feel fear. ", "The woman was afraid of what she saw. ", ""],
  ["agree", "/əˈɡriː/", "verb", "To agree is to say “yes” or to think the same way. ", "A: The food is very good in that restaurant. B : I agree with you.", ""],
  ["angry", "/ˈæŋɡri/", "adj", "When someone is angry, they may want to speak loudly or fight. ", " She didn’t do her homework, so her father is angry. ", ""],
  ["arrive", "/əˈraɪv/", "verb", "To arrive is to get to or reach some place. ", "The bus always arrives at the corner of my street at 4:00. ", ""],
  ["attack", "/əˈtæk/", "verb", "To attack is to try to fight or to hurt. ", "The man with the sword attacked the other man first. ", ""],
  ["bottom", "/ˈbɒtəm/", "adj", "The bottom is the lowest part. ", "The bottom of my shoe has a hole in it.", ""],
  ["clever", "/ˈklevə/", "adj", "When someone is clever, they can solve a hard puzzle or problem. ", "The clever boy thought of a good idea. ", ""],
  ["cruel", "/ˈkruːəl/", "adj", "When someone is cruel, they do bad things to hurt others. ", "The cruel man yelled at his sister. ", ""],
  ["finally", "/ˈfaɪnəli/", "adv", "If something happens finally, it happens aftera longtime or at the end. ", "He finally crossed the finish line after five hours of running. ", ""],
  ["hide", "/haɪd/", "verb", "To hide is to try not to let others see you. ", "The other children will hide while you count to 100. ", ""],
  ["hunt", "/hʌnt/", "verb", "To hunt is to look for or search for an animal to kill. ", "Long ago, people hunted with bows and arrows. ", ""],
  ["lot", "/lɒt/", "noun", "A lot means a large number or amount of people, animals, things, etc. ", "There are a lot of apples in the basket. ", ""],
  ["middle", "/ˈmɪdl/", "noun", "The middle of something is the center or halfway point. ", "The Canadian flag has a maple leaf in the middle of it. ", ""],
  ["moment", "/ˈməʊmənt/", "noun", "A moment is a second or a very short time. ", "I was only a few moments late for the meeting. ", ""],
  ["pleased", "/pliːzd/", "adj", "When someone is pleased, they are happy. ", " She was pleased with the phone call she received. ", ""],
  ["promise", "/ˈprɒmɪs/", "verb", "To promise is to say you will do something for sure. ", "He promised to return my key by tomorrow. ", ""],
  ["reply", "/rɪˈplaɪ/", "verb", "To reply is to give an answer or say back to someone. ", "She asked him what time his meeting was. He replied, “at three.” ", ""],
  ["safe", "/seɪf/", "adj", "When a person is safe, they are not in danger. ", "Put on your seat belt in the car to be safe. ", ""],
  ["trick", "/trɪk/", "noun", "A trick is something you do to fool another person. ", "His card trick really surprised us. ", ""],
  ["well", "/wel/", "adv", "You use well to say that something was done in a good way. ", "The couple can dance quite well. ", ""],
  ["adventure", "/ədˈventʃə/", "noun", "An adventure is a fun or exciting thing that you do. ", "Riding in the rough water was an adventure. ", ""],
  ["approach", "/əˈprəʊtʃ/", "verb", "To approach something means to move close to it. ", "The boy approached his school.", ""],
  ["carefully", "/keəfəlɪ/", "adv", "Carefully means with great attention, especially to detail or safety. ", " The baby carefully climbed down the stairs. ", ""],
  ["chemical", "/ˈkemɪkl/", "adj", "A chemical is something that scientists use in chemistry. ", "The scientist mixed the chemicals. ", ""],
  ["create", "/kriˈeɪt/", "verb", "To create means to make something new. ", " She created an igloo from blocks of snow. ", ""],
  ["evil", "/ˈiːvl/", "noun", "Evil describes something or someone bad or cruel, not good. ", "The evil figure scared us all.", ""],
  ["experiment", "/ɪkˈsperɪmənt/", "noun", "An experiment is a test that you do to see what will happen. ", "The student did an experiment in science class. ", ""],
  ["kill", "/kɪl/", "verb", "To kill someone or something is to make them die. ", " I killed the fly with a flyswatter. ", ""],
  ["laboratory", "/ləˈbɒrətrɪ/", "noun", "A laboratory is a room where a scientist works. ", "My mother works in a laboratory. ", ""],
  ["laugh", "/lɑːf/", "noun", "Laugh is the sound made when someone is happy or a funny thing occurs ", " The sound of their laugh filled the room. ", ""],
  ["loud", "/laʊd/", "adj", "If a sound is loud, it is strong and very easy to hear. ", "The man’s voice was so loud that we all could hear him. ", ""],
  ["nervous", "/ˈnɜːvəs/", "adj", "When a person is nervous, they think something bad will happen. ", "The boy became nervous when he heard the news. ", ""],
  ["noise", "/nɔɪz/", "noun", "A noise is an unpleasant sound. ", "The crying baby made a loud noise. ", ""],
  ["project", "/prəˈdʒekt/", "noun", "A project is a type of work that you do for school or a job. ", "His afternoon work project was to paint the room green. ", ""],
  ["scare", "/skeə/", "verb", "To scare someone is to make them feel afraid. ", "My uncle was scared by what he saw in the room. ", ""],
  ["secret", "/ˈsiːkrət/", "noun", "A secret is something that you do not tell other people. ", "The two boys were sharing a secret. ", ""],
  ["shout", "/ʃaʊt/", "verb", "To shout is to say something loudly. ", "My boss shouted at me because I was late for work. ", ""],
  ["smell", "/smel/", "verb", "To smell something means to use your nose to sense it. ", "The two friends smelled the flower. ", ""],
  ["terrible", "/ˈterəbl/", "adj", "If something is terrible, it is very bad. ", " The way he treated his classmate was terrible. ", ""],
  ["worse", "/wəːs/", "adj", "If something is worse, it is of poorer quality than another thing. ", "Business was worse this month than last month. ", ""],
  ["alien", "/'eɪlɪən/", "noun", "An alien is a creature from a different world. ", "The alien came in peace. ", ""],
  ["among", "/əˈmʌŋ/", "prep", "If you are among certain things, they are all around you. ", "There was a red apple among the green ones. ", ""],
  ["chart", "/tʃɑːt/", "noun", "A chart is a list of information. ", "We used a chart to see how we had improved.", ""],
  ["cloud", "/klaʊd/", "noun", "A cloud is a group of water drops in the sky. ", "The sky was filled with white clouds. ", ""],
  ["comprehend", "/ˌkɒmprɪˈhend/", "verb", "To comprehend something is to understand it. ", "Henry could not comprehend the message. ", ""],
  ["describe", "/dɪˈskraɪb/", "verb", "To describe is to say or write what someone or something is like. ", "They described their tree as colorful with gold ribbon and a star. ", ""],
  ["ever", "/ˈevə/", "adv", "Ever means at any time. ", "Going skiing last winter was the most fun I’ve ever had. ", ""],
  ["fail", "/feɪl/", "verb", "To fail means you do not succeed in what you try to do. ", "Since he failed to get the job, he was sad. ", ""],
  ["friendly", "/ˈfrendlɪ/", "adv", "Friendly is behaving in a pleasant, kind way toward someone. ", "The friendly animals came up to the girl. ", ""],
  ["grade", "/ɡreɪd/", "noun", "A grade is a score or mark given to someone’s work. ", "I managed to get good grades on my report card. ", ""],
  ["instead", "/ɪnˈsted/", "adv", "Instead means in place of. ", "He ate the carrot instead of the ice cream. ", ""],
  ["library", "/ˈlaɪbrərɪ/", "noun", "A library is a place where you go to read books. ", "The library at school is full of books. ", ""],
  ["planet", "/ˈplænɪt/", "noun", "A planet is a large round thing in space. ", "Saturn is the planet with the ring around it. ", ""],
  ["report", "/rɪˈpɔːt/", "noun", "A report is something students write for school. ", "Karen had trouble writing her report. ", ""],
  ["several", "/ˈsevrəl/", "adj", "Several is more than two but not many. ", "He had to read several books for class. ", ""],
  ["solve", "/sɒlv/", "verb", "To solve something is to find an answer to it. ", " All the students could easily solve the math problem. ", ""],
  ["suddenly", "/ˈsʌdnlɪ/", "adv", "If something happens suddenly, it happens quickly and unexpectedly. ", "I was suddenly surprised by the cake my friends brought me. ", ""],
  ["suppose", "/səˈpəʊz/", "verb", "To suppose is to guess. ", "I suppose I should go home now. ", ""],
  ["universe", "/ˈjuːnɪvɜːs/", "noun", "The universe is the known or supposed objects in space. ", "The universe is so large that it cannot be measured. ", ""],
  ["view", "/vjuː/", "verb", "To view is to look at something. ", "Michael likes to view himself in the mirror. ", ""],
  ["appropriate", "/əˈprəʊprɪət/", "adj", "When a thing is appropriate, it is right or normal. ", "It’s appropriate to wear a suit when you go to the office. ", ""],
  ["avoid", "/əˈvɔɪd/", "verb", "To avoid something is to stay away from it. ", "Avoid the broken bottle on the floor. ", ""],
  ["behave", "/bɪˈheɪv/", "verb", "To behave is to act in a particular way, especially to be good. ", "She always behaves well when her father is around. ", ""],
  ["calm", "/kɑːm/", "adj", "When someone is calm, they do not get excited or upset. ", " A nice warm bath makes me feel so calm. ", ""],
  ["concern", "/kənˈsɜːn/", "adj", "Concern is a feeling of worry. ", "I was filled with concern after reading the newspaper. ", ""],
  ["content", "/kən'tent/", "adj", "To be content is to be happy and not want more. ", "The baby looked very content sitting on the floor. ", ""],
  ["expect", "/ɪkˈspekt/", "verb", "If you expect something to happen, you believe it will happen. ", "Iexpect the bus to be here very soon.", ""],
  ["frequently", "/ˈfriːkwəntli/", "adv", "When something happens frequently, it happens often.", "We meet frequently, either at the beginning or ending of the week. ", ""],
  ["habit", "/ˈhæbɪt/", "noun", "A habit is a thing that you do often. ", " Smoking is a bad habit that can kill you. ", ""],
  ["instruct", "/ɪnˈstrʌkt/", "verb", "To instruct is to teach. ", "My teacher instructs us in several subjects. ", ""],
  ["issue", "/ˈɪʃuː/", "noun", "An issue is an important topic. ", "The men spoke about issues that were important to the people.", ""],
  ["none", "/nʌn/", "pron", "None means not any of someone or something. ", "He spent all his money. There is none left. ", ""],
  ["patient", "/patient/", "noun", "If a person is patient, they don’t become angry or upset easily.", "I had to be patient and wait until 5 o’clock to leave. ", ""],
  ["positive", "/ˈpɒzətɪv/", "adj", "If something is positive, it is good. ", "She has a positive future ahead of her after finishing college. ", ""],
  ["punish", "/ˈpʌnɪʃ/", "verb", "To punish means to make someone suffer for breaking the rules or laws. ", "To punish me, my teacher had me stand in the corner. ", ""],
  ["represent", "/ˌreprɪˈzent/", "verb", "To represent is to speak or act for a person or group. ", "My lawyer will represent me in court. ", ""],
  ["shake", "/ʃeɪk/", "adj", "To shake is to move back and forth or up and down quickly. ", "When people shake hands, it usually means they agree. ", ""],
  ["spread", "/spred/", "verb", "To spread is to move quickly to more places. ", "I like to spread butter on my toast. ", ""],
  ["stroll", "/strəʊ/", "verb", "To stroll means to walk slowly and calmly. ", "My dog and I strolled through the park today", ""],
  ["village", "/ˈvɪlɪdʒ/", "noun", "A village is a very small town. ", "There are only a few houses in my village. ", ""],
  ["aware", "/əˈweə/", "adj", "If you are aware of something, you know about it. ", " I was not aware of the ringing phone. ", ""],
  ["badly", "/ˈbædli/", "adv", "Badly means in a severe or harmful way. ", " He hurt his arm badly playing with friends. ", ""],
  ["belong", "/bɪˈlɒŋ/", "verb", "If something belongs to you, you own it.", "The blue suit belongs to Paul. ", ""],
  ["continue", "/kənˈtɪnjuː/", "verb", "To continue something is to keep doing it. ", "She stood under her umbrella as the rain continued to fall. ", ""],
  ["error", "/ˈerə/", "noun", "An error is something you do wrong. ", " I made an error on my report, so my boss was angry. ", ""],
  ["experience", "/ɪkˈspɪərɪəns/", "adj", "An experience is something you have seen or done. ", "Rock climbing was a fun experience. ", ""],
  ["field", "/fiːld/", "noun", "A field is a big area of land. ", "The field of flowers looked so pretty. ", ""],
  ["hurt", "/hɜːt/", "verb", "To hurt is to do something that makes you feel pain.", "She hurt her leg falling down the stairs. ", ""],
  ["judgment", "/dʒʌdʒmənt/", "noun", "Judgment is the ability to form opinions or decisions. ", "It’s good judgment to recycle your aluminum cans. ", ""],
  ["likely", "/ˈlaɪkli/", "adv", "If something likely happens, it will probably happen. ", "I will likely stay at home and watch TV tonight. ", ""],
  ["normal", "/ˈnɔːml/", "noun", "If something is normal, it is not strange nor surprising to you. ", " It is normal for me to bathe every night. ", ""],
  ["rare", "/reə/", "adj", "If something is rare, you do not see it very often. ", "It is rare for him to miss his flight. ", ""],
  ["relax", "/rɪˈlæks/", "verb", "To relax is to rest. ", "The frog relaxed in the warm sun. ", ""],
  ["request", "/rɪˈkwest/", "verb", "To request something is to ask for it. ", "The little girl requested a special gift from Santa Claus. ", ""],
  ["reside", "/rɪˈzaɪd/", "verb", "To reside means to live somewhere permanently or for a long time. ", "", ""],
  ["result", "/rɪˈzʌlt/", "adj", "A result is something that happens because of something else. ", "As a result of all the rain, the man had to climb on the roof. ", ""],
  ["roll", "/rəʊl/", "verb", "To roll is to move by turning over and over. ", "You must roll the ball into the pins when you bowl. ", ""],
  ["since", "/sɪns/", "prep", "Since is used to talk about a past event still happening now. ", "Since 1992, he has been driving that car. ", ""],
  ["visible", "/ˈvɪzəbl/", "adj", "If something is visible, it can be seen. ", "The moon and stars were visible in the night sky. ", ""],
  ["wild", "/waɪld/", "adj", "If something is wild, it is found in nature. ", "You should be careful around a fox, because it is a wild animal. ", ""]
];
